pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo "multi baranch pipeline build - master"
            }
        }
        stage('test') {
            steps {
                echo "multi baranch pipeline test - master"
            }
        }
        stage('deploy') {
            steps {
                echo "multi baranch pipeline deploy - master"
            }
        }
    }
}